### ISSUE TITLE
Client Xor

### ISSUE THREAD

**Issue by ipro4911** [ipro4911/WoG#4]
Todo:Fix Xor decrypt it so client can login into server,maybe need help about it

**Comment by Tbuddy12** [comment]
im trying to fix this

**Comment by Tbuddy12** [comment]
[Ogre.log](https://github.com/user-attachments/files/17693688/Ogre.log)
[OgreXMLConverter.log](https://github.com/user-attachments/files/17693689/OgreXMLConverter.log)
![screenshot10272024_173512500](https://github.com/user-attachments/assets/1b934158-d349-4a83-a201-80f942284ec4)
[autopatcher.log](https://github.com/user-attachments/files/17693690/autopatcher.log)
![screenshot03302024_123214545](https://github.com/user-attachments/assets/2f8a4f61-9701-43ce-abdd-1d946edf63b9)
![screenshot03172024_174527526](https://github.com/user-attachments/assets/e19ff109-339d-4889-bcbe-b853d7984dcb)
![screenshot12222023_171328320](https://github.com/user-attachments/assets/a718642d-90da-413b-9021-b69b0c39f969)
![screenshot12222023_171325487](https://github.com/user-attachments/assets/5f9d1c32-3cc3-445f-9cee-6846c6bfd491)
![screenshot12222023_170954026](https://github.com/user-attachments/assets/fa683d78-18c8-42b1-b16b-3ec7dda54126)

**Comment by ipro4911** [comment]
Wrong section post it in #screen-shots
